# Questo è il file di configurazione principale per Netlify.
# Definisce come il tuo sito deve essere distribuito.

[build]
  # NON è necessario un comando di build.
  # Netlify rileverà e compilerà automaticamente le funzioni nella directory specificata.
  
  # Directory che contiene le funzioni serverless.
  functions = "netlify/functions/"
  
  # Directory che contiene i file del frontend (il tuo app.html).
  publish = "public/"

[functions]
  # Specifica che le funzioni sono scritte in TypeScript e devono essere compilate.
  # L'opzione 'esbuild' è un bundler molto veloce che gestisce tutto automaticamente.
  node_bundler = "esbuild"
