[build]
  command   = "npm run build"
  functions = "functions-dist"
  publish   = "public"

[functions]
  # Usa esbuild per bundle TypeScript
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-functions-core"

[context.production.environment]
  # Variabili d'ambiente da configurare su Netlify
  APP_PASSWORD = "$APP_PASSWORD"
  JWT_SECRET = "$JWT_SECRET"
  SHOPIFY_ADMIN_API_TOKEN = "$SHOPIFY_ADMIN_API_TOKEN"
  SHOPIFY_LOCATION_ID = "$SHOPIFY_LOCATION_ID"
  SHOPIFY_STORE_NAME = "$SHOPIFY_STORE_NAME"
  SUPABASE_URL = "$SUPABASE_URL"
  SUPABASE_ANON_KEY = "$SUPABASE_ANON_KEY"
  SUPABASE_SERVICE_KEY = "$SUPABASE_SERVICE_KEY"

[dev]
  port = 8888
