# Questo file istruisce Netlify su come costruire e distribuire il sito.

[build]
  # Comando da eseguire per costruire il progetto.
  # Installa le dipendenze e compila i file TypeScript in JavaScript.
  command = "npm install && npm run build"
  
  # Directory dove si trovano le funzioni serverless compilate.
  # Netlify le distribuirà automaticamente come endpoint API.
  functions = "netlify/functions/"
  
  # Directory contenente i file statici del front-end (HTML, JS, CSS).
  publish = "public/"

# Regole di reindirizzamento per creare un'API più pulita.
[[redirects]]
  # Reindirizza tutte le chiamate da /api/* alla funzione Netlify corrispondente.
  # Esempio: una richiesta a /api/import-excel verrà gestita da netlify/functions/import-excel.js
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
